### ISSUE TITLE
This seems similar to my project!

### ISSUE THREAD

**Issue by AidanWelch** [NateTewolde/CasuallyBilingual#1]
https://github.com/AidanWelch/ProgressiveImmersion

Not an issue of course, but it's nice to see someone else is interested in a similar idea, and hopefully we can take inspiration from each other to improve both projects

**Comment by NateTewolde** [comment]
Hey thats awesome, good looking repo. I got my idea when trying to use this old chrome extension called "Mind-The-Word" that requires a google api key to use and doesnt have support for the newer languages so I'm making a new and improved version. Your api fork of google translate has been pretty helpful, appreciate that. Let me know if you have any questions or opportunities that come up
